# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  api:
    build:
      context: "C:\\ASProggs\\AutoMonitoring\\AutoMonitoring\\AutoMonitoring.Presentation"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/AutoMonitoring.Presentation.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "automonitoring.presentation:dev"
    ports: []
    volumes:
    - "C:\\Users\\Алексей\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\ASProggs\\AutoMonitoring\\AutoMonitoring\\AutoMonitoring.Presentation:/app:rw"
    - "C:\\ASProggs\\AutoMonitoring\\AutoMonitoring:/src:rw"
    working_dir: "/app"
