version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: AutoMonitoring.Presentation/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: